name: Continuous Integration
on:
  push:
    tags:
      - v1.*
      - v2.*
    branches:
      - main
      - rendered-problem-test
  pull_request:

jobs:
  scalafmt:
    name: Formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: graalvm/setup-graalvm@v1
        with:
          version: '22.3.0'
          java-version: '17'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check formatting
        run: ./bin/scalafmt --test

  integrations:
    name: Build integrations tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-15-intel]
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: true
      - uses: graalvm/setup-graalvm@v1
        with:
          version: '22.3.0'
          java-version: '17'
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: sbt/setup-sbt@v1
      - uses: coursier/cache-action@v6
      - name: Tests
        run: sbt "sbtBloop/publishLocal; sbtBloop/scripted"
        shell: bash

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-15, macos-15-intel]
        jdk: ["22.3.0", "17"]

    name: Test ${{ matrix.os }} -- ${{ matrix.jdk }}
    env:
      HYDRA_LICENSE: ${{ secrets.HYDRA_LICENSE }}

    steps:
      - uses: actions/checkout@v5
        with:
          submodules: true
          fetch-depth: 0

      - uses: coursier/setup-action@v1
        with:
          jvm: 'temurin:17'
        if: matrix.jdk == '17'
      - uses: graalvm/setup-graalvm@v1
        with:
          version: ${{ matrix.jdk }}
          java-version: '17'
        if: matrix.jdk == '22.3.0'    
      - uses: coursier/cache-action@v6
      - uses: coursier/setup-action@v1
      - uses: sbt/setup-sbt@v1
      - uses: actions/setup-node@v5
        with:
          node-version: "16"
      - name: Set up environment
        run: |
          curl -Lo coursier https://git.io/coursier-cli && chmod +x coursier && ./coursier --help
          yarn --help
          java -version
          [[ $HYDRA_LICENSE == floating-key=* ]] && mkdir -p $HOME/.triplequote && echo "$HYDRA_LICENSE" > "$HOME/.triplequote/hydra.license" || echo "Hydra license file was not created"
        shell: bash

      - name: Compile and test main projects
        run: |
          sbt \
              "frontend/test:compile; \
              backend/test; \
              docs/compile; \
              cli/compile; \
              bloopRifle/test; \
              frontend/testOnly bloop.ScalaVersionsSpec; \
              frontend/testOnly -bloop.ScalaVersionsSpec; \
              frontend/runMain bloop.util.CommandsDocGenerator --test; \
              frontend/runMain bloop.util.CommandsDocGenerator --out ../docs/cli/reference.md"
        shell: bash
